runtime: custom
env: flex
service: plataforma-test
threadsafe: true

manual_scaling:
  instances: 1

env_variables:
  API_URL: "https://www.contactemos.co"
  VARIABLE_ONE: "Variable One"
  VARIABLE_TWO: "Variable Two"
